src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[Assert\Length(min: 2,max: 50,minMessage: 'Your first name must be at least {{ limit }} characters long',maxMessage: 
    'Your first name cannot be longer than {{ limit }} characters',)]
    #[ORM\Column(type: 'string', length: 255)]
    private $nom_prenom;

    #[ORM\Column(type: 'string', length: 1)]
    private $sexe;

    #[ORM\Column(type: 'date')]
    private $date_de_naissance;

    #[ORM\Column(type: 'string', length: 255)]
    private $nationalite;

    #[ORM\ManyToMany(targetEntity: Livre::class, mappedBy: 'auteur')]
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }
public function __toString()
    {
        return $this->nom_prenom;
    }
    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->addAuteur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAuteur($this);
        }

        return $this;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $isbn;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'integer')]
    private $nombre_pages;

    #[ORM\Column(type: 'date')]
    private $date_de_parution;

    #[ORM\Column(type: 'integer')]
    private $note;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private $genre;

    #[ORM\ManyToMany(targetEntity: Auteur::class, inversedBy: 'livres')]
    private $auteur;

    public function __construct()
    {
        $this->genre = new ArrayCollection();
        $this->auteur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __toString()
    {
        return $this->getTitre();
    }
    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenre(): Collection
    {
        return $this->genre;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genre->contains($genre)) {
            $this->genre[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genre->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteur(): Collection
    {
        return $this->auteur;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteur->contains($auteur)) {
            $this->auteur[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        $this->auteur->removeElement($auteur);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn')
            ->add('titre')
            ->add('nombre_pages')
            ->add('date_de_parution')
            ->add('note')
            ->add('genre')
            ->add('auteur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\GenreRepository;
use App\Repository\AuteurRepository;

#[Route('/livre')]
class LivreController extends AbstractController
{
    #[Route('/', name: 'livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository, GenreRepository $genreRepository, AuteurRepository $auteurRepository): Response
    {
        $livres = $livreRepository->findAll();

        return $this->render('livre/index.html.twig', [
            'livres' => $livres,
            'genres' => $genreRepository->findAll(),
            'auteurs' => $auteurRepository->findAll(),
            'dates' => $livreRepository->findDates(),
        ]);
    }

    #[Route('/new', name: 'livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("/chercher/{motCle}", name="livre_chercher", methods={"GET"})
     */
    public function chercher(String $motCle, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->findByTitre($motCle);

        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/liste-entre-deux-dates/{dateMin}/{dateMax}")
     */
    public function listeEntreDeuxDates($dateMin, $dateMax, LivreRepository $livreRepository): Response
    {
        $livres = $livreRepository->findBetweenTwoDates(strval($dateMin), strval($dateMax));
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/liste-par-note/{note}", name="livre_list_by_note", methods={"GET"})
     */
    public function listByNote(LivreRepository $livreRepository, $note): Response
    {
        $livres = $livreRepository->findByNote($note);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/liste-par-date/{date}/", name="livre_list_by_date", methods={"GET"})
     */
    public function listByDate(LivreRepository $livreRepository, $date): Response
    {
        $livres = $livreRepository->findByDate($date);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }


    /**
     * @Route("/liste-par-auteur/{auteur}/", name="livre_list_by_auteur", methods={"GET"})
     */
    public function listByAuteur(LivreRepository $livreRepository, $auteur): Response
    {
        $livres = $livreRepository->findByAuteur($auteur);
        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }

    /**
     * @Route("/liste-par-genre/{genre}/", name="livre_list_by_genre", methods={"GET"})
     */
    public function listByGenre(LivreRepository $livreRepository, $genre): Response
    {
        $livres =  $livreRepository->findByGenre($genre);

        return $this->render('livre/chercher.html.twig', [
            'livres' => $livres,
        ]);
    }



}

templates/livre/_delete_form.html.twig
<form class="d-inline-block" method="post" action="{{ path('livre_delete', {'id': livre.id}) }}"
 onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
	<button class="btn btn-danger" ><i class="far fa-trash-alt"></i></button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/livre/chercher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres
{% endblock %}

{% block body %}
	{% if livres|length > 0  %}
	<div class=" container contact_section" >


		<div class="heading_container heading_center">
			<h2>
			 Résultat de votre recherche
			</h2>
		</div>

		<table id="livres" class="table">
			<thead>
				<tr>
					<th>Isbn</th>
					<th>Titre</th>
					<th>Nombre de pages</th>
					<th>Date de parution</th>
					<th>Note</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for livre in livres %}
					<tr>
						<td>{{ livre.isbn }}</td>
						<td>{{ livre.titre }}</td>
						<td>{{ livre.nombrePages }}</td>
						<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
						<td>{{ livre.note }}</td>
						<td>
							<a class="btn btn-primary" href="{{ path('livre_show', {'id': livre.id}) }}">afficher</i></a>
							{% if is_granted('ROLE_ADMIN') %}
								<a class="btn btn-primary" href="{{ path('livre_edit', {'id': livre.id}) }}">modifier</a>
								{{ include('livre/_delete_form.html.twig') }}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

	{% else %}
		<p class="alert alert-danger">Aucun résultat</p>
	{% endif %}
	</div>
{% endblock %}

{% block javascripts %}
	<script src="/js/main.js"></script>
{% endblock %}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre
{% endblock %}

{% block body %}
<div class=" container contact_section" >


	<div class="heading_container heading_center">
		<h2>
		 Modifier livre
		</h2>
	</div>

	{{ include('livre/_form.html.twig', {'button_label': 'Modifier'}) }}

	{{ include('livre/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres
{% endblock %}

{% block body %}
	
	
 <!-- slider section -->
 <section class="slider_section ">
	<div id="customCarousel1" class="carousel slide" data-ride="carousel">
	  <div class="carousel-inner">
		<div class="carousel-item active">
		  <div class="container ">
			<div class="row">
			  <div class="col-md-6">
				<div class="detail-box">
				  <h5>
					 Bookstore
				  </h5>
				  <h1>
					Vous trouverez tous types <br>
					des livres
				  </h1>
				  <p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quam velit saepe dolorem deserunt quo quidem ad optio.
				  </p>
				  <a href="{{ path('genre_index') }}">
					Voir plus
				  </a>
				</div>
			  </div>
			  <div class="col-md-6">
				<div class="img-box">
				  <img src="images/Webp.net-resizeimage.png" alt="">
				</div>
			  </div>
			</div>
		  </div>
		</div>
		<div class="carousel-item">
		  <div class="container ">
			<div class="row">
			  <div class="col-md-6">
				<div class="detail-box">
				  <h5>
					Hajar Zarguan
				  </h5>
				  <h1>
					Savois plus d'information à propos  <br>des auteurs 
				  </h1>
				  <p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste quam velit saepe dolorem deserunt quo quidem ad optio.
				  </p>
				  <a href="{{ path('auteur_index') }}">
					Savoir plus
				  </a>
				</div>
			  </div>
			  <div class="col-md-6">
				<div class="img-box">
				  <img src="images/slider-img.png" alt="">
				</div>
			  </div>
			</div>
		  </div>
		</div>

	  </div>
	  <div class="carousel_btn_box">
		<a class="carousel-control-prev" href="#customCarousel1" role="button" data-slide="prev">
		  <i class="fa fa-angle-left" aria-hidden="true"></i>
		  <span class="sr-only">precedent</span>
		</a>
		<a class="carousel-control-next" href="#customCarousel1" role="button" data-slide="next">
		  <i class="fa fa-angle-right" aria-hidden="true"></i>
		  <span class="sr-only">suivant</span>
		</a>
	  </div>
	</div>
  </section>
  <!-- end slider section -->
</div>


	
 <!-- blog section -->
 
 <section class="blog_section layout_padding"style=" background-color: white;" >
    <div class="container" >
		
      <div class="heading_container heading_center">
        <h2>
          Les livres 
        </h2>
		  
		{% if is_granted('ROLE_ADMIN') %}
		<a class="btn btn-success" style="margin-bottom: 100px;" href="{{ path('livre_new') }}"><i class="fas fa-plus"></i></a>
		{% endif %}

	
      </div>

	  
		<div class=" row ">
	
			<div class="col-md-6" >

				<form class="search_form" method="POST" onsubmit="chercher(event)">
				<input  id="motCle" type="text" class="form-control" style="border-color: blue;"
				placeholder="Chercher un livre ...">
				<button class="btn btn-primary my-2"><i class="fa fa-search"></i></button>
				</form>
			</div>

		
	
			<div class="col-md-6">
				<form class="search_form" method="POST" onsubmit="list(event)">
					<input id="dateMin" type="number" class="form-control" placeholder="date 1">
					<input id="dateMax" type="number" class="form-control" placeholder="date 2">
					<button class="btn btn-primary "><i class="fas fa-list"></i></button>
				</form>
			</div>
      	</div>


	<div class="row">
		<div class="col-md-3 "> 
			<select class="form-select mt-2" onchange="filtrerParNote(event)">
				<option selected>Note</option>
				{% for i in 0..20 %}
					<option value="{{ i }}">{{ i }}</option>
				{% endfor %}
			</select>

		</div>
		
		

		<div class="col-md-3 "> 
			<select class="form-select mt-2" onchange="filtrerParDate(event)">
				<option selected>Date de publication</option>
				{% for date in dates|sort  %}
					<option value="{{date.date_de_parution|date('m/d/Y')}}">{{date.date_de_parution|date("m/d/Y")}}</option>
				{% endfor %}
			</select>
			
		</div>
	

		<div class="col-md-3 "> 
			<select class="form-select mt-2" onchange="filtrerParAuteur(event)">
				<option selected>Auteur</option>
				{% for auteur in auteurs %}
					<option value="{{auteur.id}}">{{auteur.nomPrenom}}</option>
				{% endfor %}
			</select>
			
		</div>
		

		<div class="col-md-3 "> 

		<select class="form-select mt-2" onchange="filtrerParGenre(event)">
			<option selected>Genre</option>
			{% for genre in genres %}
				<option value="{{genre.id}}">{{genre.nom}}</option>
			{% endfor %}
		</select>	
		</div>	
		


	</div>

		
	
	

      <div class="row">


		{% for livre in livres %}
        <div class="col-sm-6 col-md-4 ">
          <div class="box">
            <div class="img-box">
            
              <h4 class="blog_date" style="background-color: cadetblue;">
                <span> {{ livre.titre }} 
					               </span>
              </h4>
            </div>
            <div class="detail-box">
              <h5>
				{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}
				
              </h5>
              <p>
				- ISBN: {{ livre.isbn }}
				  <br>
				- Nombre des pages: {{ livre.nombrePages }} pages
				<br> - Note: <span id="livre-note-{{ livre.id }}">{{ livre.note }}</span>
              </p>
            	<a  class="btn btn-info"  style="color: white;" href="{{ path('livre_show', {'id': livre.id}) }}"><i class="far fa-eye"></i></a>
						{% if is_granted('ROLE_ADMIN') %}
				<a  class="btn btn-success" style="color: white;" href="{{ path('livre_edit', {'id': livre.id}) }}"><i class="far fa-edit"></i></a>
							{{ include('livre/_delete_form.html.twig') }}
						{% endif %}
            </div>
          </div>
        </div>

		{% endfor %}

		
      </div>
    </div>
  </section>

  <!-- end blog section -->



{% endblock %}
{% block javascripts %}
	<script src="/js/main.js"></script>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre
{% endblock %}

{% block body %}
<div class=" container contact_section" >


	<div class="heading_container heading_center">
		<h2>
		 Ajouter livre
		</h2>
	</div>
	
		{{ include('livre/_form.html.twig') }}
	

</div>
	

	

{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre
{% endblock %}

{% block body %}


<div class="container" > 
	<div class="heading_container heading_center"><h1>Livre</h1></div>
	
	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ livre.id }}</td>
			</tr>
			<tr>
				<th>Isbn</th>
				<td>{{ livre.isbn }}</td>
			</tr>
			<tr>
				<th>Titre</th>
				<td>{{ livre.titre }}</td>
			</tr>
			<tr>
				<th>Nombre pages</th>
				<td>{{ livre.nombrePages }}</td>
			</tr>
			<tr>
				<th>Date de parution</th>
				<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Note</th>
				<td>{{ livre.note }}</td>
			</tr>
			<tr>
				<th>Genres</th>
				<td>
					{% for genre in livre.getGenre %}
						<span>
							{{ genre.nom }}
						</span><br>
					{% endfor %}
				</td>
			</tr>
			<tr>
				<th>Auteurs</th>
				<td>
					{% for auteur in livre.getAuteur %}
						<span>
							{{ auteur }}
						</span><br>
					{% endfor %}
				</td>
			</tr>
		</tbody>
	</table>

	{% if is_granted('ROLE_ADMIN') %}
		<a class="btn btn-primary" href="{{ path('livre_edit', {'id': livre.id}) }}">Modifier</a>
		{{ include('livre/_delete_form.html.twig') }}
	{% endif %}
</div>

{% endblock %}