src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[Assert\Length(min: 2,max: 50,minMessage: 'Your first name must be at least {{ limit }} characters long',maxMessage: 
    'Your first name cannot be longer than {{ limit }} characters',)]
    #[ORM\Column(type: 'string', length: 255)]
    private $nom_prenom;

    #[ORM\Column(type: 'string', length: 1)]
    private $sexe;

    #[ORM\Column(type: 'date')]
    private $date_de_naissance;

    #[ORM\Column(type: 'string', length: 255)]
    private $nationalite;

    #[ORM\ManyToMany(targetEntity: Livre::class, mappedBy: 'auteur')]
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }
public function __toString()
    {
        return $this->nom_prenom;
    }
    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->addAuteur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAuteur($this);
        }

        return $this;
    }
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_prenom')
            ->add('sexe')
            ->add('date_de_naissance')
            ->add('nationalite')
            ->add('livres')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Entity\Auteur;
use App\Form\AuteurType;
use App\Repository\AuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/auteur')]
class AuteurController extends AbstractController
{
    #[Route('/', name: 'auteur_index', methods: ['GET'])]
    public function index(AuteurRepository $auteurRepository): Response
    {
        return $this->render('auteur/index.html.twig', [
            'auteurs' => $auteurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'auteur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($auteur);
            $entityManager->flush();

            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/new.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'auteur_show', methods: ['GET'])]
    public function show(Auteur $auteur): Response
    {
        return $this->render('auteur/show.html.twig', [
            'auteur' => $auteur,
        ]);
    }

    #[Route('/{id}/edit', name: 'auteur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/edit.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'auteur_delete', methods: ['POST'])]
    public function delete(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$auteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($auteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/auteur/_delete_form.html.twig
<form class="d-inline-block" method="post" action="{{ path('auteur_delete', {'id': auteur.id}) }}" onsubmit="return confirm('Supprimer?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ auteur.id) }}">
	<button class="btn btn-danger" ><i class="far fa-trash-alt"></i></button>
</form>

templates/auteur/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-info">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/auteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Auteur
{% endblock %}

{% block body %}
<div class=" container contact_section" >


	<div class="heading_container heading_center">
		<h2>
		 Modifier auteur
		</h2>
	</div>

	{{ include('auteur/_form.html.twig', {'button_label': 'Modifier'}) }}
	{{ include('auteur/_delete_form.html.twig') }}
	</div>
{% endblock %}

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteurs
{% endblock %}

{% block body %}
<div class="container">
	
	<section class="client_section " style="margin-top: 100px;">
		<div class="heading_container heading_center">
			<h2>
			  Auteurs
			</h2>
		{% if is_granted('ROLE_ADMIN') %}
		<a class="btn btn-primary" href="{{ path('auteur_new') }}"><i class="fas fa-plus"></i></a>
	{% endif %}
		<div class="row">
	       {% for auteur in auteurs %}
		  
								
				<div class="col-md-3 mx-auto">
				<div class="client_container ">
					
					<div class="detail-box">
						<span>{{ auteur.id }}.</span>
					<p>
					-  {{ auteur.nomPrenom }} est né le {{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }} 
					<br>
					-  Sa nationalité est {{ auteur.nationalite }}.<br>

					<a  class="btn btn-info"  style="color: white;" href="{{ path('auteur_show', {'id': auteur.id}) }}"><i class="far fa-eye"></i></a>
						{% if is_granted('ROLE_ADMIN') %}
				<a  class="btn btn-success" style="color: white;" href="{{ path('auteur_edit', {'id': auteur.id}) }}"><i class="far fa-edit"></i></a>
							{{ include('auteur/_delete_form.html.twig') }}
						{% endif %}

					
					</p>
					<span>
						<i class="fa fa-quote-left" aria-hidden="true"></i>
					</span>
					</div>
				
				</div>
				</div>

		
		
			{% endfor %}
		</div>
		</div>
		</section>


	
	
</div>
{% endblock %}

templates/auteur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un auteur
{% endblock %}

{% block body %}
<div class=" container contact_section" >


	<div class="heading_container heading_center">
		<h2>
		 Ajouter livre
		</h2>
	</div>

	{{ include('auteur/_form.html.twig') }}
</div>
{% endblock %}

templates/auteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur
{% endblock %}

{% block body %}

<div class="container">

  <!-- client section -->

  <section class="client_section layout_padding">
    <div class="container ">
      <div class="heading_container heading_center">
        <h2>
         Auteur 
        </h2>
        <hr>
      </div>


      <div class="row">				
        <div class="col-md-6 mx-auto">
          <div class="client_container ">
			  <div class="client_id">
				<div class="img-box">
          
          {% if auteur.sexe =="M" %}
				<img src="images/c1.jpg" alt="">
           {% else %}
           <img src="images/c3.jpg" alt="">
           {% endif %}



				</div>
				<div class="client_name">
				<h5>
					{{ auteur.id }} .
				</h5>
				<span>{{ auteur.nomPrenom }}</span>
					
				</h6>
				</div>
			  </div>
            <div class="detail-box">
              <p>

               -  {{ auteur.nomPrenom }} est né le {{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }} 
			<br>
			  -  Sa nationalité est {{ auteur.nationalite }}.
			   <br> <span >Parmi ses travaux :</span> <br>

			    {% for livre in auteur.livres %}
			  <div style="margin-left: 100px;"> + {{ livre }}<br></div>
				
			  {% endfor %}
			</p>
              <span>
                <i class="fa fa-quote-left" aria-hidden="true"></i>
              </span>

              <br>
             

            {% if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-success" href="{{ path('auteur_edit', {'id': auteur.id}) }}">Modifier</a>
            {{ include('auteur/_delete_form.html.twig') }}
            {% endif %}

            </div>
          
          </div>
        </div>

        
      </div>
   
    </div>
    	

  </section>


   <!-- <td>{{ auteur.sexe }}</td>-->


</div>
{% endblock %}